# Values for the notification-clearing-api Helm Template

# Enables debug mode
debug:
  enable: ${debug_enable}

istio:
  enable: ${istio_enable}

required:
  image:
    repository: ${repository}

# Image Pull Secrets
imagePullSecrets:
  %{~ for pull_secret in image_pull_secrets ~}
  - name: ${pull_secret}
  %{~ endfor ~}

# Define custom configuration values
config:
  # The (external) Secret Objects containing the API Key entry
  secret:
    # Use default Secret from this Chart
    useDefault: false
    # The (external) Secret for API Keys
    api:
      # The name of the (external) Secret for API and the entries to be used and mapped
      name: ncapi-apikey
      entries:
        HAPI_SERVICE_APIKEY: NCS_APIKEY
    # The (external) Secret for Database
    db:
      # The name of the (external) Secret for Database and the entries to be used and mapped
      name: ncapi-database-secret
      entries:
        HAPI_DATASOURCE_PASSWORD: NOTIFICATION_DB_PASSWORD
    # The (external) Secret for CA Certificates
    cacerts:
      # The name of the (external) Secret for CA Certificates and the entries to be used and mapped
      name: postgres-tls-secret
      entries:
        postgres.crt: ca.crt
    
customEnvVars: 
  # Prevents empty values that can delete the default environment variables
  TERRAFORM_DEPLOYMENT: true
  HAPI_CORS_ALLOW_ORIGIN: "*"
  HAPI_NOTIFICATION_API_IP: "*"
  HAPI_SERVER_ADDRESS: "https://${core_hostname}${context_path}/notification-clearing-api/fhir/"
  # Deletion / Expunge Job
  HAPI_DELETION_SERVER_ADDRESS_LOCALHOST: "http://notification-clearing-api.${namespace}.svc.cluster.local/notification-clearing-api/fhir/"
  # Keycloak
  HAPI_OIDC_AUDIENCE: "notification-clearing-api"
  HAPI_OIDC_ISSUER: "https://${issuer_hostname}/realms/OEGD"
  HAPI_OIDC_KEYSOURCE: "http://${keycloak_internal_hostname}/realms/OEGD/protocol/openid-connect/certs"
  HAPI_OIDC_USERINFOENDPOINT: "http://${keycloak_internal_hostname}/realms/OEGD/protocol/openid-connect/userinfo"
  # Database
  HAPI_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQL94Dialect"
  HAPI_DATASOURCE_URL: "jdbc:postgresql://pgbouncer.${namespace}.svc.cluster.local:5432/notification"
  HAPI_DATASOURCE_USERNAME: "notification-admin"
  %{~ for flag_name, flag_value in feature_flags ~}
  ${flag_name} : ${flag_value}
  %{~ endfor ~}
  %{~ for config_name, config_value in config_options ~}
  ${config_name} : "${config_value}"
  %{~ endfor ~}


%{~ if replica_count != null ~}
# Number of Pod Replicas desired
replicaCount: ${replica_count}
%{endif}

%{~ if resource_block != null ~}
# Override Resource Definitions for Pod
${resource_block}
%{endif}