# Values for the validation-service-igs Helm Template

fullname: "${app_name}"
fullnameOverride: "${app_name}"
nameOverride: "validation-service-igs"

# Enables debug mode
debug:
  enable: ${debug_enable}

istio:
  enable: ${istio_enable}

# Required Values for the Chart
required:
  image: 
    repository: ${repository}
%{ if strcontains(repository, "gematik1") ~}
    name: demis-validation-service
%{ endif ~}
  packages:
    packageName: rki.demis.igs.snapshot
    name: igs-profile-snapshots
%{ if length(profile_versions) > 0 ~}
    versions:
%{ for version in profile_versions ~}
      - ${version}
%{ endfor ~}
%{ endif ~}
# Image Pull Secrets
imagePullSecrets: 
%{ for pull_secret in image_pull_secrets ~}
  - name: ${pull_secret}
%{ endfor ~}

customEnvVars:
  # Prevents empty values that can delete the default environment variables
  TERRAFORM_DEPLOYMENT: true
  CONFIG_OPTION_PACKAGE_REGISTRY_URL: http://package-registry.${namespace}.svc.cluster.local
%{ if length(profile_versions) == 1 ~}
  JAVA_TOOL_OPTIONS: "-XX:ActiveProcessorCount=2 -XX:MaxRAMPercentage=70.0 -XX:MaxMetaspaceSize=160m -XX:+UseG1GC"
%{ endif ~}
%{ for flag_name, flag_value in feature_flags ~}
  ${flag_name}: ${flag_value}
%{ endfor ~}
%{ for config_name, config_value in config_options ~}
  ${config_name}: "${config_value}"
%{ endfor ~}
  
podAnnotations:
  sidecar.istio.io/proxyCPU: ${istio_proxy_resources.requests.cpu}
  sidecar.istio.io/proxyMemory: ${istio_proxy_resources.requests.memory}
  sidecar.istio.io/proxyMemoryLimit: ${istio_proxy_resources.limits.memory}

%{ if replica_count != null ~}
# Number of Pod Replicas desired
replicaCount: ${replica_count}
%{ endif ~}

%{ if resource_block != null ~}
# Override Resource Definitions for Pod
${resource_block}
%{ endif ~}

%{ if resource_block == null && length(profile_versions) == 1 ~}
# Override Resource Definitions for Pod if only one profile version is provided
resources:
  limits:
    memory: "1400Mi"
  requests:
    memory: "1400Mi"
%{ endif ~}

# mode for profile provisioning of snapshot profiles
# default is dedicated
# available modes:
# - dedicated: all profiles are provisioned in a dedicated pod
# - distributed: one profile provisioning for one pod
# - combined: mix of dedicated and distributed
provisioningMode: ${provisioning_mode}

useTopologySpreadConstraints: true
