# Values for the validation-service-igs Helm Template

fullname: "validation-service-igs"
fullnameOverride: "validation-service-igs"
nameOverride: "validation-service-igs"

# Enables debug mode
debug:
  enable: ${debug_enable}

istio:
  enable: ${istio_enable}

# Required Values for the Chart
required:
  image: 
    repository: ${repository}
    %{ if strcontains(repository, "gematik1") }
    name: demis-validation-service
    %{ endif }
  profiles:
    repository: ${profile_docker_registry}
    %{ if strcontains(repository, "gematik1") }
    name: demis-igs-profile-snapshots
    %{ else }
    name: igs-profile-snapshots
    %{ endif }
    version: ${profile_version}

# Image Pull Secrets
imagePullSecrets: 
  %{~ for pull_secret in image_pull_secrets ~}
  - name: ${pull_secret}
  %{~ endfor ~}
  
customEnvVars:
  # Prevents empty values that can delete the default environment variables
  TERRAFORM_DEPLOYMENT: true
  %{~ for flag_name, flag_value in feature_flags ~}
  ${flag_name} : ${flag_value}
  %{~ endfor ~}
  %{~ for config_name, config_value in config_options ~}
  ${config_name} : "${config_value}"
  %{~ endfor ~}

%{~ if replica_count != null ~}
# Number of Pod Replicas desired
replicaCount: ${replica_count}
%{endif}

%{~ if resource_block != null ~}
# Override Resource Definitions for Pod
${resource_block}
%{endif}