# Values for surveillance-pseudonym-service-ars
fullname: "surveillance-pseudonym-service-ars"
fullnameOverride: "surveillance-pseudonym-service-ars"
nameOverride: "surveillance-pseudonym-service-ars"

# Enables debug mode
debug:
  enable: ${debug_enable}

istio:
  enable: ${istio_enable}
  
required:
  image: 
    repository: ${repository}
    %{ if strcontains(repository, "gematik1") }
    name: demis-surveillance-pseudonym-service
    %{ endif }

# Image Pull Secrets
imagePullSecrets: 
  %{~ for pull_secret in image_pull_secrets ~}
  - name: ${pull_secret}
  %{~ endfor ~}
  
# IMPORTANT: these values must be defined in the Secret Objects
config:
  # The (external) Secret Objects containing the API Key entry
  secrets:
    # Use default Secret from this Chart
    useDefault: false

secret:
  dbPwdUser:
    name: ars-pseudo-user-database-secret
    key: ARS_PSEUDO_USER_DB_PASSWORD
  dbPwdDdl:
    name: ars-pseudo-ddl-database-secret
    key: ARS_PSEUDO_DDL_DB_PASSWORD
  hashPepper:
    name: ars-pseudo-hash-pepper
    key: ARS_PSEUDO_HASH_PEPPER

customEnvVars:
  # Prevents empty values that can delete the default environment variables
  TERRAFORM_DEPLOYMENT: true
  DB_URL: "jdbc:postgresql://pgbouncer.${namespace}.svc.cluster.local:5432/surveillance-pseudonym"
  DB_USER: ars-pseudo-user
  LIQUIBASE_DB_USER: ars-pseudo-ddl
  %{~ for flag_name, flag_value in feature_flags ~}
  ${flag_name} : ${flag_value}
  %{~ endfor ~}
  %{~ for config_name, config_value in config_options ~}
  ${config_name} : "${config_value}"
  %{~ endfor ~}

%{~ if replica_count != null ~}
# Number of Pod Replicas desired
replicaCount: ${replica_count}
%{endif}

%{~ if resource_block != null ~}
# Override Resource Definitions for Pod
${resource_block}
%{endif}