# Values for the surveillance-pseudonym-purger-ars Helm Template
fullname: "surveillance-pseudonym-purger-ars"
fullnameOverride: "surveillance-pseudonym-purger-ars"
nameOverride: "surveillance-pseudonym-purger-ars"

# Enables debug mode
debug:
  enable: ${debug_enable}

istio:
  enable: ${istio_enable}

# Defines the Schedule for the CronJob
cronJobSchedule: "${cron_schedule}"

required:
  image: 
    repository: ${repository}
    %{ if strcontains(repository, "gematik1") }
    name: demis-surveillance-pseudonym-purger
    %{ endif }
  suspend: ${suspend}

# Image Pull Secrets
imagePullSecrets: 
  %{~ for pull_secret in image_pull_secrets ~}
  - name: ${pull_secret}
  %{~ endfor ~}
  
secret:
  name: ars-pseudo-purger-database-secret
  key: ARS_PSEUDO_PURGER_DB_PASSWORD

# Extra Environment Variables to be defined
customEnvVars:
  # preserves default environment variables from helm chart
  TERRAFORM_DEPLOYMENT: true
  DB_URL: "jdbc:postgresql://pgbouncer.${namespace}.svc.cluster.local:5432/surveillance-pseudonym"
  DB_USER: ars-pseudo-purger
  %{~ for flag_name, flag_value in feature_flags ~}
  ${flag_name} : ${flag_value}
  %{~ endfor ~}
  %{~ for config_name, config_value in config_options ~}
  ${config_name} : "${config_value}"
  %{~ endfor ~}


%{~ if replica_count != null ~}
# Number of Pod Replicas desired
replicaCount: ${replica_count}
%{endif}

%{~ if resource_block != null ~}
# Override Resource Definitions for Pod
${resource_block}
%{endif}
