# Do not create Istio Resources for this Application
create: false
# Application Information
appName: "certificate-update-service"
appNamespace: "${namespace}" # defaults to Release.Namespace
# Do not create a Service for this Application
appServiceEnabled: false