# Enables debug mode
debug:
  enable: ${debug_enable}

istio:
  enable: ${istio_enable}

required:
  image: 
    repository: ${repository}
    %{ if strcontains(repository, "gematik1") }
    name: demis-postgres
    %{ endif }

# Image Pull Secrets
imagePullSecrets: 
  %{~ for pull_secret in image_pull_secrets ~}
  - name: ${pull_secret}
  %{~ endfor ~}

podAnnotations: 
  checksum/postgres-tls: ${postgres_tls_secret_checksum}
  checksum/db-secret: ${db_secret_checksum}
  
customEnvVars:
  # Prevents empty values that can delete the default environment variables
  TERRAFORM_DEPLOYMENT: true
  CONFIG_KEYCLOAK_DB: false
  CONFIG_BUNDID_DB: false
  CONFIG_PSEUDO_DB: ${pseudo_db_enabled}
  CONFIG_SURVEILLANCE_PSEUDO_DB: ${surveillance_pseudo_db_enabled}
  CONFIG_ARS_PSEUDO_SCHEMA: ${ars_pseudo_schema_enabled}
  CONFIG_DESTINATION_LOOKUP_DB: ${destination_lookup_db_enabled}
  CONFIG_FHIR_STORAGE_DB: ${fhir_storage_db_enabled}
  %{~ for flag_name, flag_value in feature_flags ~}
  ${flag_name}: ${flag_value}
  %{~ endfor ~}
  %{~ for config_name, config_value in config_options ~}
  ${config_name}: ${config_value}
  %{~ endfor ~}

extraEnvVars:
%{ if fhir_storage_db_enabled ~}
  - name: FHIR_STORAGE_WRITER_DDL_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: fhir-storage-writer-ddl-database-secret
        key: FHIR_STORAGE_WRITER_DDL_DB_PASSWORD
  - name: FHIR_STORAGE_PURGER_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: fhir-storage-purger-database-secret
        key: FHIR_STORAGE_PURGER_DB_PASSWORD
  - name: FHIR_STORAGE_WRITER_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: fhir-storage-writer-database-secret
        key: FHIR_STORAGE_WRITER_DB_PASSWORD
  - name: FHIR_STORAGE_READER_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: fhir-storage-reader-database-secret
        key: FHIR_STORAGE_READER_DB_PASSWORD
%{ endif ~}
%{ if pseudo_db_enabled ~}
  - name: PSEUDO_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pseudo-database-secret
        key: PSEUDO_DB_PASSWORD
%{ endif ~}
%{ if ars_pseudo_schema_enabled ~}
  - name: ARS_PSEUDO_DDL_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ars-pseudo-ddl-database-secret
        key: ARS_PSEUDO_DDL_DB_PASSWORD
  - name: ARS_PSEUDO_USER_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ars-pseudo-user-database-secret
        key: ARS_PSEUDO_USER_DB_PASSWORD
  - name: ARS_PSEUDO_PURGER_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ars-pseudo-purger-database-secret
        key: ARS_PSEUDO_PURGER_DB_PASSWORD
%{ endif ~}
%{ if destination_lookup_db_enabled ~}
  - name: DESTINATION_LOOKUP_WRITER_DDL_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: destination-lookup-writer-ddl-database-secret
        key: DESTINATION_LOOKUP_WRITER_DDL_DB_PASSWORD
  - name: DESTINATION_LOOKUP_PURGER_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: destination-lookup-purger-database-secret
        key: DESTINATION_LOOKUP_PURGER_DB_PASSWORD
  - name: DESTINATION_LOOKUP_WRITER_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: destination-lookup-writer-database-secret
        key: DESTINATION_LOOKUP_WRITER_DB_PASSWORD
  - name: DESTINATION_LOOKUP_READER_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: destination-lookup-reader-database-secret
        key: DESTINATION_LOOKUP_READER_DB_PASSWORD
%{ endif ~}

%{~ if replica_count != null ~}
# Number of Pod Replicas desired
replicaCount: ${replica_count}
%{endif}

%{~ if resource_block != null ~}
# Override Resource Definitions for Pod
${resource_block}
%{endif}
