# Values for the pdfgen-service Helm Template
# Enables debug mode
debug:
  enable: ${debug_enable}

istio:
  enable: ${istio_enable}

required:
  image: 
    repository: ${repository}
    %{ if strcontains(repository, "gematik1") }
    name: demis-report-processing-service
    %{ endif }

# Image Pull Secrets
imagePullSecrets: 
  %{~ for pull_secret in image_pull_secrets ~}
  - name: ${pull_secret}
  %{~ endfor ~}
  
customEnvVars:
  # Prevents empty values that can delete the default environment variables
  TERRAFORM_DEPLOYMENT: true
  DEMIS_NETWORK_VALIDATION_SERVICE_ADDRESS: http://validation-service.${namespace}.svc.cluster.local
  DEMIS_NETWORK_FHIR_STORAGE_WRITER_ADDRESS: http://fhir-storage-writer.${namespace}.svc.cluster.local/notification-clearing-api/fhir
  DEMIS_NETWORK_HOSPITAL_LOCATION_SERVICE_ADDRESS: http://hospital-location-service.${namespace}.svc.cluster.local
  DEMIS_NETWORK_PDFGEN_SERVICE_ADDRESS: http://pdfgen-service.${namespace}.svc.cluster.local
  DEMIS_NETWORK_CONTEXT_ENRICHMENT_SERVICE_ADDRESS: http://context-enrichment-service.${namespace}.svc.cluster.local
  %{~ for flag_name, flag_value in feature_flags ~}
  ${flag_name} : ${flag_value}
  %{~ endfor ~}
  %{~ for config_name, config_value in config_options ~}
  ${config_name} : "${config_value}"
  %{~ endfor ~}


%{~ if replica_count != null ~}
# Number of Pod Replicas desired
replicaCount: ${replica_count}
%{endif}

%{~ if resource_block != null ~}
# Override Resource Definitions for Pod
${resource_block}
%{endif}