# Values for the validation-service-igs Helm Template

fullname: "validation-service-ars"
fullnameOverride: "validation-service-ars"
nameOverride: "validation-service-ars"

# Enables debug mode
debug:
  enable: ${debug_enable}

istio:
  enable: ${istio_enable}

# Required Values for the Chart
required:
  image: 
    repository: ${repository}
%{ if strcontains(repository, "gematik1") ~}
    name: demis-validation-service
%{ endif ~}
  profiles:
    repository: ${profile_docker_registry}
%{ if strcontains(repository, "gematik1") && profile_handling_api_version == "v1" ~}
    name: demis-ars-profile-snapshots
%{ else ~}
%{ if strcontains(repository, "gematik1") && profile_handling_api_version == "v2" ~}
    name: ars-profile-snapshots
    imageName: demis-ars-profile-snapshots
%{ else ~}
    name: ars-profile-snapshots
%{ endif ~}
%{ endif ~}
    version: ${profile_version}
%{ if length(profile_versions) > 0 ~}
    versions: 
%{ for version in profile_versions ~}
      - ${version}
%{ endfor ~}
%{ endif ~}

# Image Pull Secrets
imagePullSecrets: 
%{ for pull_secret in image_pull_secrets ~}
  - name: ${pull_secret}
%{ endfor ~}
  
customEnvVars:
  # Prevents empty values that can delete the default environment variables
  TERRAFORM_DEPLOYMENT: true
%{ for flag_name, flag_value in feature_flags ~}
  ${flag_name}: ${flag_value}
%{ endfor ~}
%{ for config_name, config_value in config_options ~}
  ${config_name}: "${config_value}"
%{ endfor ~}


%{ if replica_count != null ~}
# Number of Pod Replicas desired
replicaCount: ${replica_count}
%{ endif ~}

%{ if resource_block != null ~}
# Override Resource Definitions for Pod
${resource_block}
%{ endif ~}

%{ if profile_handling_api_version == "v2" ~}
# mode for profile provisioning of snapshot profiles
# default is dedicated
# available modes:
# - dedicated: all profiles are provisioned in a dedicated pod
# - distributed: one profile provisioning for one pod
# - combined: mix of dedicated and distributed
provisioningMode: ${provisioning_mode}
%{ else ~}
${labels}
%{ endif ~}