{
 "title": "log(error) generisch",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "loki" },
   {
    "name": "namespace",
    "query": {}
   },
   {
    "name": "app",
    "label": "app",
    "query": {}
   },
   {
    "name": "noErrorRegex",
    "query": "`(Unknown code '20422'|RestExceptionHandler activated|Failed to find ADMIN theme|Failed to find ACCOUNT theme|Revoked on:|Failed to load evidences of disease! No data found. Disease: cdfd|LVS-001|LifecycleValidationException: No valid scenario found|Error when retrieving getInfoForCodeFromCodeSystem|Certificate's been revoked|REFRESH_TOKEN_ERROR|user_not_found|Error while loading code|misc:error|StructureDefinition|\"severity\":\"WARN\"|errorCode=FHIR_VALIDATION_ERROR|LIFECYCLE_VALIDATION_ERROR|Failed to load evidences of disease!|entered-in-error)`"
   }
  ]
 },
 "panels": [
  { "title": "sum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "nginx",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(status) (count_over_time( {app=\"log-collector-nginx\"} !~ `(curl|zgrab|uptimerobot|Exporter|Datadog|check_http|Zabbix|PRTG|Site24x7|probing)` | regexp `\\\"(?P<method>[A-Z]+) (?P<path>[^\\s]+) (?P<http_version>HTTP\\/\\d\\.\\d)\\\" (?P<status>\\d+) (?P<size>\\d+) \"[^\"]+\" \"(?P<ua>[^\"]+)\"` | status != \"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "nginx 5xx",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(status) (count_over_time( {app=\"log-collector-nginx\"} | regexp `\\\"(?P<method>[A-Z]+) (?P<path>[^\\s]+) (?P<http_version>HTTP\\/\\d\\.\\d)\\\" (?P<status>\\d+) (?P<size>\\d+)` | status >= 500 [$__interval]))"
    }
   ]
  },
  { "title": "Alarme", "type": "alertlist", "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 } },
  {
   "title": "DB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(severity) (count_over_time({app=\"log-collector-db\"} != `Last completed transaction was` !~ `restartpoint|checkpoint|recovery|connection` [$__interval]))"
    }
   ]
  },
  { "title": "error summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "$app",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "repeat": "app",
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"$app\"} |~ `(?i)error` !~ $noErrorRegex [$__interval]))"
    }
   ]
  },
  {
   "title": "nginx 5xx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "nginx 5xx",
     "type": "logs",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": " {app=\"log-collector-nginx\"} | regexp `\\\"(?P<method>[A-Z]+) (?P<path>[^\\s]+) (?P<http_version>HTTP\\/\\d\\.\\d)\\\" (?P<status>\\d+) (?P<size>\\d+)` | status >= 500"
      }
     ]
    }
   ]
  },
  {
   "title": "DB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB",
     "type": "logs",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "{app=\"log-collector-db\"} != `Last completed transaction was` !~ `restartpoint|checkpoint|recovery|connection`"
      }
     ]
    }
   ]
  },
  {
   "title": "$app log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "app",
   "collapsed": true,
   "panels": [
    {
     "title": "$app",
     "type": "logs",
     "gridPos": { "h": 21, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "{app=\"$app\"} |~ `(?i)error` !~ $noErrorRegex"
      }
     ]
    }
   ]
  }
 ]
}