{
 "title": "Uwes Kurven",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "query": "loki" },
   { "name": "http_status", "label": "http status (als regex)", "query": "[^23].." },
   {
    "name": "regex_exclude",
    "label": "exclude (regex)",
    "query": "(Telegraf|checkmk-active-httpv2|9explore|GoogleOther|Googlebot|gptbot|HetrixTools|HTTPing|curl|zgrab|uptimerobot|Exporter|Datadog|check_http|Zabbix|PRTG|Site24x7|probing|Uptime-Kuma)"
   },
   { "name": "regex_include", "label": "include only (regex)", "query": "." }
  ]
 },
 "panels": [
  {
   "title": "nginx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(status) (count_over_time( {app=\"log-collector-nginx\"} |~ `$regex_include` !~ `$regex_exclude` | regexp `\\\"(?P<method>[A-Z]+) (?P<path>[^\\s]+) (?P<http_version>HTTP\\/\\d\\.\\d)\\\" (?P<status>\\d+) (?P<size>\\d+) \"[^\"]+\" \"(?P<ua>[^\"]+)\"` | status != \"\" | status =~ `$http_status` [$__interval]))"
    }
   ]
  },
  {
   "title": "nginx",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(status) (count_over_time( {app=\"log-collector-nginx\"} |~ `$regex_include` !~ `$regex_exclude` | regexp `\\\"(?P<method>[A-Z]+) (?P<path>[^\\s]+) (?P<http_version>HTTP\\/\\d\\.\\d)\\\" (?P<status>\\d+) (?P<size>\\d+) \"[^\"]+\" \"(?P<ua>[^\"]+)\"` | status != \"\" | status =~ `$http_status` [$__interval]))"
    }
   ]
  },
  {
   "title": "POST des Meldeportal",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(url) (count_over_time({container=\"log-collector-nginx\"} |= `access` |= `POST /gateway` | regexp `\"(?P<method>[A-Z]+) (?P<path>[^\"]+) HTTP/(?P<http_version>[\\d.]+)\" (?P<status>\\d+) (?P<size>\\d+) \"(?P<url>[^\"]+)\" \"[^\"]+\" ` [$__interval]))"
    }
   ]
  },
  {
   "title": "POST des Meldeportal",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(url) (count_over_time({container=\"log-collector-nginx\"} |= `access` |= `POST /gateway` | regexp `\"(?P<method>[A-Z]+) (?P<path>[^\"]+) HTTP/(?P<http_version>[\\d.]+)\" (?P<status>\\d+) (?P<size>\\d+) \"(?P<url>[^\"]+)\" \"[^\"]+\" ` [$__interval]))"
    }
   ]
  },
  {
   "title": "Uwe seine super-spezial Auswertung",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "notification-gateway error",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(message) (count_over_time({container=\"notification-gateway\"} | json | __error__=\"\" | severity = `ERROR` | regexp `\\\"Error message: (?P<message>[^\"]+)` | message =~ `.+` [$__interval]))"
    }
   ]
  },
  {
   "title": "spezial ModSec Zeichenkettensuche",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum by(msg) (count_over_time({container=\"log-collector-nginx\"} |= `ModSecurity` !~ `(GET https://portal.demis.rki.de/portal/ HTTP/1.0|PUT /sequence-data)` | regexp `id \"(?P<id>\\d+)\".+msg \"(?P<msg>[^\\\"]*)\"` | id !~ `(949110)` [$__interval]))"
    }
   ]
  },
  {
   "title": "KeyCloak user error",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum by(user, error) (count_over_time({container=\"keycloak\"} |~ `$regex_include` !~ `$regex_exclude`| json | __error__!=\"JSONParserErr\" | level != `INFO` | regexp `username=\\\\\"(?P<user>[^\\\\]+)\\\\\"` | regexp `error=\\\\\"(?P<error>[^\\\\]+)\\\\\"` | user!=`` [$__interval]))"
    }
   ]
  },
  {
   "title": "4xx producer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(ip, status) (count_over_time({container=\"log-collector-nginx\"} |~ `$regex_include` !~ `$regex_exclude` | regexp ` \"log\"=>\"(?P<ip>[^ ]+) .*\\\"(?P<method>[A-Z]+) (?P<path>[^\\s]+) (?P<http_version>HTTP\\/\\d\\.\\d)\\\" (?P<status>\\d+) (?P<size>\\d+) \"[^\"]+\" \"(?P<ua>[^\"]+)\"` | status != `` | status =~ `(4..)` [$__interval]))"
    }
   ]
  },
  {
   "title": "422 producer@nps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by(sender) (count_over_time({container=\"notification-processing-service\"} |~ `$regex_include` !~ `$regex_exclude` |= `status=422` | regexp ` from sender (?P<sender>[0-9]+) ` [$__interval]))"
    }
   ]
  },
  {
   "title": "User Agents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "POST auf fhir|token (ohne 200)",
     "type": "state-timeline",
     "gridPos": { "h": 23, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum by(ua,status) (rate({app=\"log-collector-nginx\"} |~ `$regex_include` !~ `$regex_exclude` |= `POST` |~ `(fhir|token)` | regexp `\\\"(?P<method>[A-Z]+) (?P<path>[^\\s]+) (?P<http_version>HTTP\\/\\d\\.\\d)\\\" (?P<status>\\d+) (?P<size>\\d+) \"[^\"]+\" \"(?P<ua>[^\"]+)\"` | http_version != `` | status != `200` | status =~ `$http_status` [$__interval]))"
      }
     ]
    }
   ]
  },
  {
   "title": "nginx log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "nginx",
     "type": "logs",
     "gridPos": { "h": 39, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "{app=\"log-collector-nginx\"} |~ `$regex_include` !~ `$regex_exclude` | regexp `\\\"(?P<method>[A-Z]+) (?P<path>[^\\s]+) (?P<http_version>HTTP\\/\\d\\.\\d)\\\" (?P<status>\\d+) (?P<size>\\d+) \"[^\"]+\" \"(?P<ua>[^\"]+)\"` | status != \"\" | status =~ `$http_status`"
      }
     ]
    }
   ]
  }
 ]
}