# Values for the pseudoymization-service Helm Template
# Enables debug mode
debug:
  enable: ${debug_enable}

istio:
  enable: ${istio_enable}

required:
  image: 
    repository: ${repository}
    %{ if strcontains(repository, "gematik1") }
    name: demis-pseudonymization-service
    %{ endif }

# Image Pull Secrets
imagePullSecrets: 
  %{~ for pull_secret in image_pull_secrets ~}
  - name: ${pull_secret}
  %{~ endfor ~}
  
# Define custom configuration values
# The Entries will be read from the given (external) Secrets and injected in the container with the same name.
# IMPORTANT: these values must be defined in the Secret Objects
config:  
  # The (external) Secret Objects containing the API Key entry
  secret:
    # Use default Secret from this Chart
    useDefault: false
    # The (external) Secret for Database Password
    db:
      # The name of the (external) Secret for Database and the key to be used
      name: pseudo-database-secret
      key: PSEUDO_DB_PASSWORD

customEnvVars: 
  # Prevents empty values that can delete the default environment variables
  TERRAFORM_DEPLOYMENT: true
  DB_URL: "jdbc:postgresql://pgbouncer.${namespace}.svc.cluster.local:5432/pseudonymization"
  DB_USERNAME: "pseudo-admin"
  %{~ for flag_name, flag_value in feature_flags ~}
  ${flag_name} : ${flag_value}
  %{~ endfor ~}
  %{~ for config_name, config_value in config_options ~}
  ${config_name} : "${config_value}"
  %{~ endfor ~}


%{~ if replica_count != null ~}
# Number of Pod Replicas desired
replicaCount: ${replica_count}
%{endif}

%{~ if resource_block != null ~}
# Override Resource Definitions for Pod
${resource_block}
%{endif}