# Default values for portal-shell

istio:
  enable: ${istio_enable}

required:
  image: 
    repository: ${repository}
    %{ if strcontains(repository, "gematik1") }
    name: demis-portal-shell
    %{ endif }

# Image Pull Secrets
imagePullSecrets: 
  %{~ for pull_secret in image_pull_secrets ~}
  - name: ${pull_secret}
  %{~ endfor ~}
  
# Extra Environment Variables to be defined
# customEnvVars
#   key: value
customEnvVars:
  PORTAL_CSP_HOSTNAME: "${csp_hostname}"

# Set parameters as production mode, etc.
# if production mode is true, hex-hex button won't be shown
config:
  production: ${production_mode}
  idp:
    - baseUrl: https://${issuer_hostname}
      tenant: demis
      issuers:
        - https://${issuer_hostname}/realms/HOSPITAL
    - baseUrl: https://${issuer_hostname}
      tenant: demis-portal
      clientId: meldeportal
      clientIdInternet: meldeportal-internet
      meldungDNS: https://${meldung_hostname}
      issuers:
        - https://${issuer_hostname}/realms/PORTAL
  featureFlags:
    # Prevents empty values that can delete the default environment variables
    "TERRAFORM_DEPLOYMENT": true
    %{~ for flag_name, flag_value in feature_flags ~}
    "${flag_name}" : ${flag_value}
    %{~ endfor ~}
    %{~ for config_name, config_value in config_options ~}
    "${config_name}" : ${config_value}
    %{~ endfor ~}
    

%{~ if replica_count != null ~}
# Number of Pod Replicas desired
replicaCount: ${replica_count}
%{endif}

%{~ if resource_block != null ~}
# Override Resource Definitions for Pod
${resource_block}
%{endif}